spring:
  # ===================================================================
  # Datasource configuration
  # ===================================================================
  datasource:
    url: jdbc:postgresql://localhost:5432/db-rate
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: mysecretpassword
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  port: 8087

file:
  upload:
    root: ${user.home}/Projects/xStay/upload-folder
    identity-document-image: ${file.upload.root}/guests/:guestId/identity-documents/
